### ISSUE TITLE
按照文档编译以后，commit2还是本地机器完成的，没有到API上？

### ISSUE THREAD

**Issue by yuwenhui** [DeepBrainChain/DBC-lotus#1]
会是什么原因呢？编译这块麻烦给个详细的说明，谢谢。

**Comment by sbwtw** [comment]
lotus 使用 v0.4.0-webapi 分支，注意 extern 目录下的 filecoin-ffi submodule 也要用 DeepBrainChain 的 filecoin-ffi，使用 ca281af0b6c00314-webapi 分支。

**Comment by yuwenhui** [comment]
extren目录下的filecoin-ffi-origin还需要编译吗？我看DBC-lotus里面也引用了filecoin-ffi-origin，不编译filecoin-ffi-origin的话，编译lotus会报错，提示找不到filcrypto.pc这个文件。

**Comment by yuwenhui** [comment]
![image](https://user-images.githubusercontent.com/1715211/86885886-9a4fe000-c128-11ea-8717-e04966ea5fb5.png)
我按照这个文档操作的，extren目录下的filecoin-ffi-origin还需要编译吗？我看DBC-lotus里面也引用了filecoin-ffi-origin，不编译filecoin-ffi-origin的话，编译lotus会报错，提示找不到filcrypto.pc这个文件。
